server:
  # 端口
  port: 8081

spring: #springboot的配置
  datasource: #定义数据源
    #127.0.0.1为本机测试的ip，3306是mysql的端口号。serverTimezone是定义时区，照抄就好，mysql高版本需要定义这些东西
    #useSSL也是某些高版本mysql需要问有没有用SSL连接
    url: jdbc:mysql://47.108.163.167:3306/test?serverTimezone=GMT%2B8&useSSL=FALSE
    username: root  #数据库用户名，root为管理员
    password: 18224026250Mn #该数据库用户的密码
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.zxh.blog.entity
  type-aliases-super-type: java.lang.Object
  type-handlers-package: com.zxh.blog.typeHandler
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler